FROM noorul/python-sjsclient-ft

RUN git clone https://github.com/spark-jobserver/spark-jobserver /opt/spark-jobserver

WORKDIR /opt/spark-jobserver

RUN sbt job-server-extras/assembly && sbt job-server-tests/package && sbt buildPyExamples

COPY ci/start.sh start.sh

COPY . .
